import os
import glob
import time
import pandas as pd
from pathlib import Path
from core.config import ScraperSettings
from core.logger import get_logger

class ExcelCleaner:
    """
    Utility class to handle legacy Excel files (.xls) generated by third-party vendor systems.
    It converts them to modern .xlsx format and cleans up messy, irregular headers 
    so the data can be reliably processed by downstream pandas operations.
    """
    def __init__(self, settings: ScraperSettings, target_folder_name: str, target_sheet_name: str):
        self.settings = settings
        self.target_folder_name = target_folder_name
        self.target_sheet_name = target_sheet_name
        
        self.logger = get_logger(f"CLEANER_{target_folder_name}", self.settings.region_code)
        
        # Leveraging the base_dir from settings to keep paths DRY and environment-agnostic
        self.target_dir = self.settings.base_dir / self.settings.region_code / self.target_folder_name

    def find_header_and_fix(self, df: pd.DataFrame) -> pd.DataFrame | None:
        """
        External vendor exports often include useless metadata rows at the top. 
        This method scans the first 20 rows to dynamically locate the actual header row 
        (identified by the specific anchor keyword) and truncates the garbage data above it.
        """
        header_idx = -1
        limit_rows = min(20, len(df))
        
        for i in range(limit_rows):
            cell_value = str(df.iat[i, 0]).strip().lower()
            if "keyword_x" in cell_value:
                header_idx = i
                break
                
        if header_idx != -1:
            self.logger.debug(f"Found actual data header at row {header_idx + 1}")
            new_header = df.iloc[header_idx] 
            df_cleaned = df[header_idx + 1:].copy()
            df_cleaned.columns = new_header
            df_cleaned.reset_index(drop=True, inplace=True)
            return df_cleaned
        else:
            # Failsafe: If we can't find the header, we abort to prevent corrupting the dataset
            self.logger.warning("Target anchor 'Keyword_X' not found in early rows. Skipping file to prevent data loss.")
            return None

    def convert_and_replace(self):
        """
        Main execution loop. Scans for legacy .xls files, cleans them, saves as .xlsx, 
        and safely removes the originals to prevent duplicate processing.
        """
        self.logger.info(f"Scanning target directory: {self.target_dir}")
        
        if not self.target_dir.exists():
            self.logger.error(f"Target directory does not exist: {self.target_dir}")
            return

        # Explicitly looking only for old .xls files to avoid touching already processed .xlsx files
        xls_files = [f for f in glob.glob(os.path.join(self.target_dir, "*.xls")) if not f.lower().endswith(".xlsx")]
        
        if not xls_files:
            self.logger.info("No legacy .xls files found. Folder is clean.")
            return

        self.logger.info(f"Found {len(xls_files)} files. Starting conversion sequence...")

        for filename in xls_files:
            base_name = os.path.basename(filename)
            new_filename = filename + "x" # Simple string append turns .xls into .xlsx
            
            self.logger.info(f"Processing: {base_name}...")
            
            try:
                # 'xlrd' engine is explicitly required to read old Excel formats
                with pd.ExcelFile(filename, engine='xlrd') as xls:
                    if self.target_sheet_name not in xls.sheet_names:
                        self.logger.warning(f"SKIPPING: Required sheet '{self.target_sheet_name}' not found. Available sheets: {xls.sheet_names}")
                        continue
                    df = pd.read_excel(xls, sheet_name=self.target_sheet_name, header=None)
                
                cleaned_df = self.find_header_and_fix(df)

                if cleaned_df is not None:
                    # Write the cleaned data to the modern format
                    with pd.ExcelWriter(new_filename, engine='openpyxl') as writer:
                        cleaned_df.to_excel(writer, sheet_name=self.target_sheet_name, index=False)
                    
                    # Safety check: Only delete the original if the new file was successfully written
                    if os.path.exists(new_filename) and os.path.getsize(new_filename) > 0:
                        try:
                            os.remove(filename)
                            self.logger.info("Success! Converted to .xlsx and deleted the original legacy file.")
                        except PermissionError:
                            # Edge case: Windows sometimes holds onto the file lock a bit too long. 
                            # A short sleep and retry usually solves it.
                            time.sleep(1)
                            try:
                                os.remove(filename)
                                self.logger.info("Success on retry! Original legacy file deleted.")
                            except Exception as e:
                                self.logger.warning(f"Conversion successful, but OS locked the original file. Could not delete: {e}")
                    else:
                        self.logger.error("New file failed to write properly. Keeping the original file safe.")
                        
            except Exception as e:
                self.logger.error(f"FAILED processing {base_name}: {e}")

        self.logger.info("--- Folder Cleaning Process Complete ---")

if __name__ == "__main__":
    # Example execution block for standalone testing
    settings = ScraperSettings(region_code="REGION_TEST")
    
    vendor_a_cleaner = ExcelCleaner(settings, target_folder_name="VENDOR_A_DATA", target_sheet_name="Data_Sheet")
    vendor_a_cleaner.convert_and_replace()
    
    vendor_b_cleaner = ExcelCleaner(settings, target_folder_name="VENDOR_B_DATA", target_sheet_name="Data_Sheet")
    vendor_b_cleaner.convert_and_replace()